### ISSUE TITLE
Transfer repo from openwallet-foundation-labs to openwallet-foundation

### ISSUE THREAD

**Issue by tkuhrt** [openwallet-foundation/governance#21]
Transfer https://github.com/openwallet-foundation-labs/sd-jwt-js to https://github.com/openwallet-foundation.

@ryjones : Can you confirm these steps?
1. [x] Remove repository from openwallet-foundation-labs/governance/config.yaml
2. [x] Transfer repo
3. [x] Update openwallet-foundation/governance/config.yaml with teams and repo (as previously existed in openwallet-foundation-labs/governance/config.yaml)

**Comment by ryjones** [comment]
yes
